### ISSUE TITLE
Compatibility with other models

### ISSUE THREAD

**Issue by not-filepile** [dx-dtran/gpt2-mlx#4]
Will this script work on other models as well?
(like llama or mistral)

**Comment by dx-dtran** [comment]
Hi @FilePile2856, I didn't design the training script with other models in mind -- the GPT-2 model is hard coded into the script [here](https://github.com/dx-dtran/gpt2-mlx/blob/main/train.py#L82). But in theory, if you have an MLX definition of another model, you can use that model in the script. You would replace that line in the script with your new model
